### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by jrb130130**
First attempt at GitHub

### CODE REVIEW

**Comment by jhc100020** [comment]
Hey Jessie is Github working for everyone?

**Comment by jrb130130** [comment]
I was trying to figure out how to use the GUI client but didn’t quite figure it out. I was able to push some files but then I didn’t know what to do afterwards, lol. There are currently my rough draft in progress SRs on there that I was working on and using for testing.

The only other person ive seen make a fork off it was Sainath

**Comment by jhc100020** [comment]
Well if Github is not a good choice its not to late to use something else

On Sep 27, 2015 12:06 PM, jrb130130 notifications@github.com wrote:

I was trying to figure out how to use the GUI client but didn't quite figure it out. I was able to push some files but then I didn't know what to do afterwards, lol. There are currently my rough draft in progress SRs on there that I was working on and using for testing.

The only other person ive seen make a fork off it was Sainath

**Comment by jrb130130** [comment]
Yeah I am thinking google drive might be the answer.. 99% of people have a gmail, and it allows for un-delete, and im 50% sure I recall revision control. Sainath Volunteered for the cost analysis part, im not sure if it was ALL of it, or if that’s too big/too little of a portion for him.

So I started the SR, you can go look at them if you want. They focus primarily on that green sheet I gave you. I renamed it “information sheet” and a few other things on there. I need to finalize the form its in but for now its readable I think. Ineed to go back and work on the gui stuff. Even if we don’t build a gui it is needed for the project.

**Pull request merged**
